name: capes_env
channels:
  - conda-forge
  - defaults
dependencies:
  - plotly
  - pandas
  - jupyterlab
  - ipywidgets
  - ipython
  - pathlib
  - numpy
  - networkx
  - qgrid
  - matplotlib
  - h5py

